theatre_homepage:
    path:     /
    defaults: { _controller: theBundle:Default:articles }

theatre_articles:
    path:     /articles
    defaults: { _controller: theBundle:Default:articles }

theatre_zeus:
    path:     /zeus
    defaults: { _controller: theBundle:Default:zeus }

theatre_admin:
    path:     /admin
    defaults: { _controller: theBundle:Admin:admin }

theatre_ajouteArticle:
    path:     /ajouteArticle
    defaults: { _controller: theBundle:Admin:ajouteArticle }
theatre_ajouteArticleZeus:
    path:     /ajouteArticleZeus
    defaults: { _controller: theBundle:Admin:ajouteArticleZeus }

theatre_modifierArticle:
    path:     /modifierArticle/{id}
    defaults: { _controller: theBundle:Admin:modifierArticle, id: 1 }
theatre_modifierArticleZeus:
    path:     /modifierArticleZeus/{id}
    defaults: { _controller: theBundle:Admin:modifierArticleZeus, id: 1 }
    
theatre_effacerArticle:
    path:     /effacerArticle/{id}
    defaults: { _controller: theBundle:Admin:effacerArticle, id: 1 }
    
theatre_effacerArticleZeus:
    path:     /effacerArticleZeus/{id}
    defaults: { _controller: theBundle:Admin:effacerArticleZeus, id: 1 }

theatre_billeterie:
    path:     /billeterie/{numPlace}
    defaults: { _controller: theBundle:Default:billeterie,numPlace:-1 }
theatre_panier:
    path:     /panier
    defaults: { _controller: theBundle:Default:panier }
theatre_interesse:
    path:     /interesse
    defaults: { _controller: theBundle:Default:interesse }
theatre_contact:
    path:     /contact
    defaults: { _controller: theBundle:Default:contact }
    requirements:
        _method:  GET|POST