<?php

namespace theBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ZeusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZeusRepository extends EntityRepository {

    public function getOrderedArticles() {
       return $this->getEntityManager()->createQuery(
                       "SELECT a FROM theBundle:Zeus a "
                        . "ORDER BY a.date ASC"
        );
    }

}
